"""unique user uuis

Revision ID: d6001fbf3f1e
Revises: 09da9c99d25d
Create Date: 2025-12-24 10:11:03.175557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6001fbf3f1e'
down_revision: Union[str, Sequence[str], None] = '09da9c99d25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_account_user_uuid', 'user_account', ['user_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_account_user_uuid', 'user_account', type_='unique')
    # ### end Alembic commands ###
